#!/usr/bin/env python3
"""Render `cargo llvm-cov --json` into COVERAGE.md.

The point of the report is the *lowest-covered files* table, which CLAUDE.md
calls the standing to-do surface. A bare percentage tells a contributor nothing
about where to go next; a ranked list of the files with the most uncovered lines
tells them exactly that.

Ranked by uncovered *lines* rather than by percentage, deliberately. A 40%-covered
20-line module is a rounding error; a 75%-covered 900-line state machine is where
the untested behaviour actually is, and sorting by percentage buries it.
"""

import json
import sys
from pathlib import Path


def repo_relative(path: str, root: Path) -> str:
    """Trim the absolute path llvm-cov emits down to something clickable."""
    try:
        return str(Path(path).resolve().relative_to(root))
    except ValueError:
        # Outside the repo: a dependency compiled with coverage instrumentation.
        # Kept rather than dropped, so an unexpected entry is visible instead of
        # silently shaping the totals.
        return path


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: coverage_report.py <llvm-cov json>", file=sys.stderr)
        return 2

    root = Path(__file__).resolve().parent.parent
    with open(sys.argv[1], encoding="utf-8") as handle:
        report = json.load(handle)

    if not report.get("data"):
        print("no coverage data in the report", file=sys.stderr)
        return 1

    data = report["data"][0]
    totals = data["totals"]
    lines = totals["lines"]
    functions = totals["functions"]
    regions = totals["regions"]

    files = []
    for entry in data.get("files", []):
        summary = entry["summary"]["lines"]
        if summary["count"] == 0:
            # No executable lines: a module of pure declarations. Including it
            # would report 0% for a file with nothing to cover.
            continue
        files.append(
            {
                "path": repo_relative(entry["filename"], root),
                "covered": summary["covered"],
                "count": summary["count"],
                "percent": summary["percent"],
                "missed": summary["count"] - summary["covered"],
            }
        )

    out = []
    out.append("# Coverage")
    out.append("")
    out.append(
        "Generated by `make coverage`. Merged across every test manifest, so a line "
        "covered only by the simulator still counts — most of the core's coverage "
        "comes from propsim driving it, and a per-crate report understates it badly."
    )
    out.append("")
    out.append("Advisory, not gating: `make coverage-check` enforces a soft floor and is")
    out.append("deliberately not part of `make check`. Treat a drop on a file you edited as")
    out.append("a defect to fix before declaring done.")
    out.append("")
    out.append("| Metric | Covered | Total | % |")
    out.append("|---|---|---|---|")
    for name, metric in (
        ("Lines", lines),
        ("Functions", functions),
        ("Regions", regions),
    ):
        out.append(
            f"| {name} | {metric['covered']} | {metric['count']} | "
            f"{metric['percent']:.1f}% |"
        )
    out.append("")

    out.append("## Lowest-covered files")
    out.append("")
    out.append(
        "Ranked by uncovered lines, not by percentage: a 40%-covered 20-line module is a "
        "rounding error, while a 75%-covered state machine is where the untested behaviour is."
    )
    out.append("")
    out.append("| File | Uncovered | Total | % |")
    out.append("|---|---|---|---|")
    for entry in sorted(files, key=lambda f: f["missed"], reverse=True)[:15]:
        out.append(
            f"| [{entry['path']}]({entry['path']}) | {entry['missed']} | "
            f"{entry['count']} | {entry['percent']:.1f}% |"
        )
    out.append("")

    out.append("## Every file")
    out.append("")
    out.append("| File | Covered | Total | % |")
    out.append("|---|---|---|---|")
    for entry in sorted(files, key=lambda f: f["path"]):
        out.append(
            f"| [{entry['path']}]({entry['path']}) | {entry['covered']} | "
            f"{entry['count']} | {entry['percent']:.1f}% |"
        )
    out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
